# https://docs.docker.com/compose/compose-file/

services:
  flights:
    build:
      context: .
      dockerfile: deployment/flights.Dockerfile
    environment:
      - SKYVIZ_ENV=dev
    volumes:
      - type: bind
        source: ./src/flights/config/groups/secrets.py
        target: /app/src/flights/config/groups/secrets.py
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres:15.3
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flights_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  skyviz:
    build:
      context: .
      dockerfile: deployment/skyviz.Dockerfile
    environment:
      - SKYVIZ_ENV=dev
    volumes:
      - type: bind
        source: ./src/skyviz/config/groups/secrets.py
        target: /app/src/flights/config/groups/secrets.py
    ports:
      - 8501:8501
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8501" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
