# https://setuptools.pypa.io/en/latest/userguide/quickstart.html

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "flights"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "requests == 2.30.0",
    "pytest == 7.3.1",
    "alembic == 1.11.1",
    "flake8",
]
