# https://setuptools.pypa.io/en/latest/userguide/quickstart.html

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sky-viz"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "flake8",
    "mypy",
    "types-requests",
    "hydra-core == 1.3.2",
    "pytest == 7.3.1",
    "requests == 2.30.0",
    "alembic == 1.11.1",
    "psycopg[binary] == 3.1.9",
    "streamlit == 1.22.0",
]

[tool.pytest.ini_options]
# switch commented line to test other module
addopts = "--ignore=tests/skyviz"
# addopts = "--ignore=tests/flights"
