# https://www.pulumi.com/docs/using-pulumi/continuous-delivery/github-actions/
name: Pulumi prod stack

env:
  SKYVIZ_ENV: prod
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  POSTGRES_PROD_ADMIN_USERNAME: ${{ secrets.POSTGRES_PROD_ADMIN_USERNAME }}
  POSTGRES_PROD_ADMIN_PASSWORD: ${{ secrets.POSTGRES_PROD_ADMIN_PASSWORD }}

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: python3 -m venv .venv
      - run: source .venv/bin/activate
      - run: pip install .
      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: prod
          work-dir: deployment
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}